services:
  - type: web
    name: alugai-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python api/app.py
    envVars:
      - key: PORT
        value: 5020
      - key: DEBUG
        value: "false"

