services:
  - type: web
    name: alugai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && python app.py
    envVars:
      - key: PORT
        value: 5020
      - key: DEBUG
        value: "false"

